[package]
name = "sm64gs2pc"
version = "0.1.0"
authors = ["Benjamin Levy <blevy@protonmail.com>"]
edition = "2018"

[dependencies]
sm64gs2pc-core = { path = "../sm64gs2pc-core" }
structopt = "0.3.16"
bincode = "1.3.1"
lazy_static = "1.4.0"

[build-dependencies]
reqwest = "0.10.7"
tokio = "0.2.22"
