# Based on https://github.com/actions-rs/example/blob/master/.github/workflows

on: [push, pull_request]

name: Checks

jobs:
  checks:
    name: Checks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Get base ROM
        uses: actions/checkout@v2
        with:
          repository: sm64gs2pc/roms
          token: ${{ secrets.ROMS_CLONE_TOKEN }}
          path: roms

      - name: Move base ROM to repo root
        run: mv roms/baserom.us.z64 .

      - name: Install dependencies
        run: |
          sudo apt install libclang-10-dev build-essential git binutils-mips-linux-gnu python3 libaudiofile-dev
          wget https://github.com/n64decomp/qemu-irix/releases/download/v2.11-deb/qemu-irix-2.11.0-2169-g32ab296eef_amd64.deb -O qemu-irix.deb
          sudo dpkg --install qemu-irix.deb

      - name: Install nightly Rust toolchain (for grcov)
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: nightly

      - name: Install stable Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          default: true

      # Clippy needs to be run first so that warnings become CI failures

      - name: Run cargo clippy
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: -- -D warnings

      - name: Run cargo clippy --all-features
        uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --all-features -- -D warnings

      - name: Run cargo check
        uses: actions-rs/cargo@v1
        with:
          command: check

      - name: Run cargo check --all-features
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all-features

      - name: Run cargo test
        uses: actions-rs/cargo@v1
        with:
          command: test

      - name: Run cargo test --all-features
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: --all-features
        env:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: -Zprofile -Ccodegen-units=1 -Cinline-threshold=0 -Clink-dead-code -Coverflow-checks=off -Cpanic=abort -Zpanic_abort_tests
          RUSTDOCFLAGS: -Cpanic=abort

      - name: Run cargo fmt
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Gather coverage data
        id: coverage
        uses: actions-rs/grcov@v0.1
        with:
          config: .github/actions-rs/grcov.yml

      - name: Coveralls upload
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path-to-lcov: ${{ steps.coverage.outputs.report }}
